// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// blm_cpp
Rcpp::List blm_cpp(const arma::mat& Y, const arma::mat& X, const int& S, const Rcpp::List& prior);
RcppExport SEXP _btse_blm_cpp(SEXP YSEXP, SEXP XSEXP, SEXP SSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(blm_cpp(Y, X, S, prior));
    return rcpp_result_gen;
END_RCPP
}
// bvar_cpp
Rcpp::List bvar_cpp(const arma::mat Y, const int k, const int S, const Rcpp::List prior);
RcppExport SEXP _btse_bvar_cpp(SEXP YSEXP, SEXP kSEXP, SEXP SSEXP, SEXP priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type prior(priorSEXP);
    rcpp_result_gen = Rcpp::wrap(bvar_cpp(Y, k, S, prior));
    return rcpp_result_gen;
END_RCPP
}
// matnrnd_cpp
arma::mat matnrnd_cpp(const arma::mat& M, const arma::mat& U, const arma::mat& V);
RcppExport SEXP _btse_matnrnd_cpp(SEXP MSEXP, SEXP USEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(matnrnd_cpp(M, U, V));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_btse_blm_cpp", (DL_FUNC) &_btse_blm_cpp, 4},
    {"_btse_bvar_cpp", (DL_FUNC) &_btse_bvar_cpp, 4},
    {"_btse_matnrnd_cpp", (DL_FUNC) &_btse_matnrnd_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_btse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
