# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bayesian linear model with natural conjugate prior
#'
#' A|Sigma ~ MN(A_l, V_l, Sigma), Sigma ~ IW(S_l, v_l)
#'
NULL

#' Bayesian linear model with independent prior
#'
#' vec_A ~ N(vec_A_l, V_l), Sigma ~ IW(S_l, v_l)
#' y|vec_A,Sigma ~ N(Z*vec_A, I_T \otimes Sigma)
#'
NULL

blm_conjugate_cpp <- function(Y, X, S, prior) {
    .Call(`_btse_blm_conjugate_cpp`, Y, X, S, prior)
}

blm_independent_cpp <- function(Y, X, S, burn, thin, prior) {
    .Call(`_btse_blm_independent_cpp`, Y, X, S, burn, thin, prior)
}

#' Bayesian vector autoregression
#'
NULL

.bvar_cpp <- function(Y, k, model, S, burn, thin, prior) {
    .Call(`_btse_bvar_cpp`, Y, k, model, S, burn, thin, prior)
}

#' Estimate impulse response function
#'
NULL

.estimate_irf_cpp <- function(posterior, periods, structural = TRUE) {
    .Call(`_btse_estimate_irf_cpp`, posterior, periods, structural)
}

#' Long-run restriction identification
#'
#' Transform VAR(k) to VMA(infty) then compute Choleski decomposition
#'
#' @name identify_long_run_cpp
#'
NULL

.identify_longrun_cpp <- function(posterior) {
    .Call(`_btse_identify_longrun_cpp`, posterior)
}

#' Short-run restriction identification
#'
#' Choleski decomposition with ordering
#'
#' @name identify_shortrun_cpp
#'
NULL

.identify_shortrun_cpp <- function(posterior) {
    .Call(`_btse_identify_shortrun_cpp`, posterior)
}

#' Sign restriction identification
#'
#' Draw orthonormal matrices Q until the sign restrictions are satisfied
#'
#' @name identify_sign_cpp
#'
NULL

.identify_sign_cpp <- function(posterior, sign) {
    .Call(`_btse_identify_sign_cpp`, posterior, sign)
}

