# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bayesian linear model
#'
#' Bayesian linear regression with normal-inverse-Wishart conjugate prior
#' prior: B ~ MN(B_0, V_0, Sigma), Sigma ~ IW(Lambda_0, nu_0)
#'
#' @param Y dependent variables
#' @param X independent variables
#' @param S sample size
#' @param prior list of priors
#'
NULL

blm_cpp <- function(Y, X, S, prior) {
    .Call(`_btse_blm_cpp`, Y, X, S, prior)
}

#' Bayesian vector autoregression
#'
NULL

.bvar_cpp <- function(Y, p, S, prior) {
    .Call(`_btse_bvar_cpp`, Y, p, S, prior)
}

#' Estimate impulse response function
#'
NULL

.estimate_irf_cpp <- function(posterior, periods) {
    .Call(`_btse_estimate_irf_cpp`, posterior, periods)
}

#' Long-run restriction identification
#'
#' Transform VAR(p) to VMA(infty) then compute Choleski decomposition
#'
NULL

.identify_longrun_cpp <- function(posterior) {
    .Call(`_btse_identify_longrun_cpp`, posterior)
}

#' Short-run restriction identification
#'
#' Choleski decomposition with ordering
#'
NULL

.identify_shortrun_cpp <- function(posterior) {
    .Call(`_btse_identify_shortrun_cpp`, posterior)
}

#' Sign restriction identification
#'
#' Draw orthonormal matrices Q until the sign restrictions are satisfied
#'
NULL

.identify_sign_cpp <- function(posterior, sign) {
    .Call(`_btse_identify_sign_cpp`, posterior, sign)
}

